import { StyleSheet } from 'react-native';
 
export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#102127',
  },
  screenContainer: {
    flex: 1,
  },
  content: {
    padding: 22,
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  eyebrow: {
    color: '#7fa7aa',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.5,
  },
  title: {
    color: '#f4f0e7',
    fontSize: 32,
    fontWeight: '800',
    marginTop: 5,
  },
  stationBadge: {
    alignItems: 'center',
    backgroundColor: '#1d343a',
    borderRadius: 20,
    flexDirection: 'row',
    gap: 7,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  statusDot: { borderRadius: 5, height: 9, width: 9 },
  liveDot: { backgroundColor: '#59c3c3' },
  demoDot: { backgroundColor: '#e8c56a' },
  stationText: { color: '#d7e5df', fontSize: 11, fontWeight: '800', letterSpacing: 1 },
  hero: {
    backgroundColor: '#21434a',
    borderRadius: 24,
    overflow: 'hidden',
    padding: 24,
  },
  heroOrb: {
    backgroundColor: '#28545a',
    borderRadius: 100,
    height: 160,
    position: 'absolute',
    right: -50,
    top: -55,
    width: 160,
  },
  heroLabel: { color: '#91c8c3', fontSize: 11, fontWeight: '800', letterSpacing: 1.4 },
  heroValue: { color: '#f4f0e7', fontSize: 42, fontWeight: '800', marginTop: 8 },
  heroCopy: { color: '#c1d8d2', fontSize: 14, marginTop: 4 },
  updatedRow: { alignItems: 'center', flexDirection: 'row', marginTop: 25 },
  pulse: { backgroundColor: '#59c3c3', borderRadius: 4, height: 8, marginRight: 8, width: 8 },
  updatedText: { color: '#a9c8c2', fontSize: 12 },
  alert: { alignItems: 'center', backgroundColor: '#492f35', borderRadius: 16, flexDirection: 'row', marginTop: 14, padding: 15 },
  alertIcon: { alignItems: 'center', backgroundColor: '#ef7d88', borderRadius: 14, color: '#492f35', fontSize: 18, fontWeight: '900', height: 28, lineHeight: 28, textAlign: 'center', width: 28 },
  alertBody: { marginLeft: 12, flex: 1 },
  alertTitle: { color: '#ffe6e4', fontSize: 14, fontWeight: '800' },
  alertCopy: { color: '#d7acae', fontSize: 12, marginTop: 3 },
  alertDetailCard: { alignItems: 'center', backgroundColor: '#183139', borderRadius: 16, flexDirection: 'row', marginBottom: 10, padding: 14 },
  alertDetailBody: { marginLeft: 12, flex: 1 },
  alertDetailTitle: { color: '#f4f0e7', fontSize: 14, fontWeight: '800' },
  alertDetailCopy: { color: '#91afb0', fontSize: 12, marginTop: 3 },
  emptyState: { alignItems: 'center', backgroundColor: '#183139', borderRadius: 20, marginTop: 10, padding: 34 },
  emptyBadge: { alignItems: 'center', backgroundColor: '#59c3c322', borderRadius: 28, height: 56, justifyContent: 'center', width: 56 },
  emptyBadgeText: { color: '#59c3c3', fontSize: 15, fontWeight: '900' },
  emptyTitle: { color: '#f4f0e7', fontSize: 17, fontWeight: '800', marginTop: 16 },
  emptyCopy: { color: '#91afb0', fontSize: 13, marginTop: 6, textAlign: 'center' },
  sectionHeading: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12, marginTop: 27 },
  sectionTitle: { color: '#f4f0e7', fontSize: 19, fontWeight: '800' },
  refreshButton: { backgroundColor: '#d5e9dc', borderRadius: 18, minWidth: 74, paddingHorizontal: 14, paddingVertical: 8 },
  pressed: { opacity: 0.7 },
  refreshText: { color: '#15252b', fontSize: 12, fontWeight: '800', textAlign: 'center' },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  metricCard: { backgroundColor: '#183139', borderRadius: 18, minHeight: 147, padding: 16, width: '48%' },
  metricTop: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  metricIcon: { alignItems: 'center', borderRadius: 10, height: 32, justifyContent: 'center', width: 43 },
  metricIconText: { fontSize: 10, fontWeight: '900' },
  healthDot: { borderRadius: 4, height: 8, width: 8 },
  metricLabel: { color: '#91afb0', fontSize: 12, marginTop: 16 },
  metricValue: { color: '#f4f0e7', fontSize: 25, fontWeight: '800', marginTop: 3 },
  metricUnit: { color: '#719092', fontSize: 11, marginTop: 1 },
  connectionRow: { alignItems: 'center', backgroundColor: '#d5e9dc', borderRadius: 18, flexDirection: 'row', marginTop: 24, padding: 15 },
  connectionMark: { alignItems: 'center', backgroundColor: '#a9d2c3', borderRadius: 12, height: 42, justifyContent: 'center', width: 42 },
  connectionMarkText: { color: '#21434a', fontSize: 12, fontWeight: '900' },
  connectionBody: { flex: 1, marginLeft: 12 },
  connectionTitle: { color: '#21434a', fontSize: 14, fontWeight: '800' },
  connectionCopy: { color: '#527572', fontSize: 11, marginTop: 3 },
  connectionChevron: { color: '#527572', fontSize: 27, fontWeight: '300', marginLeft: 8 },
  settingsRow: { alignItems: 'center', backgroundColor: '#183139', borderRadius: 16, flexDirection: 'row', marginBottom: 10, padding: 15 },
  settingsBody: { flex: 1 },
  settingsTitle: { color: '#f4f0e7', fontSize: 14, fontWeight: '800' },
  settingsCopy: { color: '#91afb0', fontSize: 12, marginTop: 3 },
  tabBar: {
    alignItems: 'center',
    backgroundColor: '#0c1a1f',
    borderTopColor: '#1d343a',
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingBottom: 10,
    paddingTop: 10,
  },
  tabButton: { alignItems: 'center', flex: 1, gap: 4, paddingVertical: 4 },
  tabButtonPressed: { opacity: 0.6 },
  tabIconWrap: { position: 'relative' },
  tabIcon: {
    alignItems: 'center',
    backgroundColor: '#183139',
    borderRadius: 12,
    height: 34,
    justifyContent: 'center',
    width: 44,
  },
  tabIconActive: { backgroundColor: '#59c3c333' },
  tabIconText: { color: '#7fa7aa', fontSize: 9, fontWeight: '900' },
  tabIconTextActive: { color: '#59c3c3' },
  tabBadge: {
    backgroundColor: '#ef7d88',
    borderRadius: 4,
    height: 8,
    position: 'absolute',
    right: -2,
    top: -2,
    width: 8,
  },
  tabLabel: { color: '#7fa7aa', fontSize: 11, fontWeight: '700' },
  tabLabelActive: { color: '#f4f0e7' },
 
  screenSubtitle: { color: '#7fa7aa', fontSize: 13, marginTop: 4 },
 
  alertsSummaryCard: {
    borderRadius: 18,
    marginBottom: 20,
    padding: 18,
  },
  alertsSummaryCardActive: {
    backgroundColor: '#21434a',
    borderLeftColor: '#ef7d88',
    borderLeftWidth: 4,
  },
  alertsSummaryCardClear: {
    backgroundColor: '#183139',
    borderLeftColor: '#59c3c3',
    borderLeftWidth: 4,
  },
  alertsSummaryTitle: { color: '#f4f0e7', fontSize: 17, fontWeight: '800' },
  alertsSummaryCopy: { color: '#c1d8d2', fontSize: 13, marginTop: 6 },
 
  alertItemCard: {
    backgroundColor: '#183139',
    borderRadius: 18,
    borderTopWidth: 3,
    marginBottom: 14,
    padding: 16,
  },
  alertItemCardCritical: { borderTopColor: '#ef7d88' },
  alertItemCardWarning: { borderTopColor: '#e8c56a' },
  alertItemHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
  },
  alertIconCircle: {
    alignItems: 'center',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    marginRight: 12,
    width: 36,
  },
  alertIconCircleCritical: { backgroundColor: '#ef7d8822' },
  alertIconCircleWarning: { backgroundColor: '#e8c56a22' },
  alertIconCircleText: { fontSize: 16 },
  alertItemTitleWrap: { flex: 1 },
  alertItemTitle: { color: '#f4f0e7', fontSize: 15, fontWeight: '800' },
  alertItemBadgeCritical: {
    color: '#ef7d88',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.6,
    marginTop: 3,
  },
  alertItemBadgeWarning: {
    color: '#e8c56a',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.6,
    marginTop: 3,
  },
  alertItemTime: { color: '#719092', fontSize: 11, marginLeft: 8 },
  alertItemMessage: { color: '#c1d8d2', fontSize: 13, marginTop: 12 },
 
  thresholdRow: {
    backgroundColor: '#102127',
    borderRadius: 12,
    flexDirection: 'row',
    marginTop: 14,
    padding: 12,
  },
  thresholdCol: { flex: 1 },
  thresholdLabel: {
    color: '#719092',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.6,
  },
  thresholdValue: { color: '#f4f0e7', fontSize: 12, fontWeight: '700', marginTop: 4 },
 
  clearAllButton: {
    alignItems: 'center',
    backgroundColor: '#21434a',
    borderRadius: 18,
    marginTop: 8,
    paddingVertical: 16,
  },
  clearAllButtonDisabled: { backgroundColor: '#183139', opacity: 0.5 },
  clearAllButtonText: { color: '#f4f0e7', fontSize: 15, fontWeight: '800' },
 
  settingsSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
    marginTop: 22,
  },
  settingsSectionHeaderIcon: { fontSize: 13 },
  settingsSectionHeaderText: {
    color: '#91afb0',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  settingsGroupCard: {
    backgroundColor: '#183139',
    borderRadius: 18,
    overflow: 'hidden',
  },
  settingsRowInner: {
    alignItems: 'center',
    flexDirection: 'row',
    padding: 15,
  },
  settingsRowDivider: {
    borderTopColor: '#0f2229',
    borderTopWidth: 1,
  },
  settingsIconBadge: {
    alignItems: 'center',
    borderRadius: 12,
    height: 40,
    justifyContent: 'center',
    marginRight: 13,
    width: 40,
  },
  settingsIconBadgeText: { fontSize: 17 },
  settingsRowBody: { flex: 1 },
  settingsRowTitle: { color: '#f4f0e7', fontSize: 14, fontWeight: '800' },
  settingsRowSubtitle: { color: '#91afb0', fontSize: 11, marginTop: 3 },
  settingsDatePill: {
    alignItems: 'center',
    backgroundColor: '#ef7d8822',
    borderRadius: 10,
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  settingsDatePillText: { color: '#ef7d88', fontSize: 13, fontWeight: '800' },
  logoutButton: {
    alignItems: 'center',
    backgroundColor: '#c04a4a',
    borderRadius: 18,
    marginTop: 26,
    paddingVertical: 16,
  },
  logoutButtonText: { color: '#fff0ef', fontSize: 15, fontWeight: '800' },
 
  authScroll: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 24,
  },
  authHeader: { alignItems: 'center', marginBottom: 28 },
  authLogoCircle: {
    alignItems: 'center',
    backgroundColor: '#21434a',
    borderRadius: 24,
    height: 72,
    justifyContent: 'center',
    width: 72,
  },
  authLogoEmoji: { fontSize: 32 },
  authAppName: { color: '#f4f0e7', fontSize: 24, fontWeight: '800', marginTop: 14 },
  authTagline: { color: '#7fa7aa', fontSize: 12, marginTop: 4 },
  authCard: {
    backgroundColor: '#183139',
    borderRadius: 24,
    padding: 22,
  },
  authCardTitle: { color: '#f4f0e7', fontSize: 22, fontWeight: '800' },
  authCardSubtitle: { color: '#91afb0', fontSize: 13, marginBottom: 22, marginTop: 4 },
  inputGroup: { marginBottom: 16 },
  inputLabel: {
    color: '#7fa7aa',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    marginBottom: 7,
  },
  inputRow: {
    alignItems: 'center',
    backgroundColor: '#102127',
    borderRadius: 14,
    flexDirection: 'row',
    paddingHorizontal: 14,
  },
  textInput: { color: '#f4f0e7', flex: 1, fontSize: 14, paddingVertical: 14 },
  showToggle: { paddingHorizontal: 4, paddingVertical: 8 },
  showToggleText: { color: '#59c3c3', fontSize: 12, fontWeight: '800' },
  fieldErrorText: { color: '#ef7d88', fontSize: 11, marginTop: 6 },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#59c3c3',
    borderRadius: 16,
    marginTop: 6,
    paddingVertical: 16,
  },
  primaryButtonDisabled: { opacity: 0.5 },
  primaryButtonText: { color: '#0c1a1f', fontSize: 15, fontWeight: '800' },
  authLinkRow: { alignItems: 'center', marginTop: 16 },
  authLinkText: { color: '#91afb0', fontSize: 13 },
  authLinkAccent: { color: '#59c3c3', fontWeight: '800' },
  secondaryButton: {
    alignItems: 'center',
    borderColor: '#2b444b',
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 14,
    paddingVertical: 14,
  },
  secondaryButtonText: { color: '#d7e5df', fontSize: 14, fontWeight: '800' },
 
  modalOverlay: {
    alignItems: 'center',
    backgroundColor: '#00000099',
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  modalCard: {
    backgroundColor: '#183139',
    borderRadius: 22,
    padding: 22,
    width: '100%',
  },
  modalButtonRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  modalButtonHalf: { flex: 1, marginTop: 0 },
});
 